# Generated by Django 5.1.4 on 2024-12-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
